import { HttpDrivers } from '@providers/HttpProvider/HttpDrivers';
export const apiKey =
  'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1YTZlNjEyMDFhMGEwMmU3M2I5ZDhmOGQwMWNmODM5ZiIsInN1YiI6IjVlYTFiNWNlZTk0MmJlMDAxZjFmNGY0ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.tzDUVdlauEcqE18otG5J9ShtoKYrdAmkHVv1kbotD7U';

export const httpDriverDefault = HttpDrivers.Axios;
